version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.7.2
        environment:
          MIX_ENV: prod
    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - mix-packages-{{ checksum "mix.lock" }}
            - mix-packages-{{ .Branch }}
            - mix-packages
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}
            - build-cache
      - run: mix deps.get
      - save_cache:
          key: mix-packages-{{ checksum "mix.lock" }}
          paths: deps
      - save_cache:
          key: mix-packages-{{ .Branch }}
          paths: deps
      - save_cache:
          key: mix-packages
          paths: deps
      - run: mix compile
      - save_cache:
          key: build-cache-{{ .Branch }}
          paths: _build
      - save_cache:
          key: build-cache
          paths: _build
      - run: mix release
      - persist_to_workspace:
          root: _build/prod/rel/websflyer
          paths: releases
  deploy_staging:
    parallelism: 1
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: sudo pip install awscli
      - run: |
          echo 'export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY_STAGING"' >> $BASH_ENV
          echo 'export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID_STAGING"' >> $BASH_ENV
          echo 'export REVISION=$(echo $CIRCLE_SHA1 | cut -c -9)' >> $BASH_ENV
          source $BASH_ENV
      - run: aws s3 cp /tmp/workspace/releases/$REVISION/websflyer.tar.gz s3://fave-websflyer-ci-builds-staging/releases/$REVISION.tar.gz
  deploy_production:
    parallelism: 1
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: sudo pip install awscli
      - run: |
          echo 'export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY_PRODUCTION"' >> $BASH_ENV
          echo 'export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID_PRODUCTION"' >> $BASH_ENV
          echo 'export REVISION=$(echo $CIRCLE_SHA1 | cut -c -9)' >> $BASH_ENV
          source $BASH_ENV
      - run: aws s3 cp /tmp/workspace/releases/$REVISION/websflyer.tar.gz s3://fave-websflyer-ci-builds-production/releases/$REVISION.tar.gz
workflows:
  version: 2
  build_then_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy_production:
          requires:
            - build
          filters:
            tags:
              only: /production/
            branches:
              ignore: /.*/
      - deploy_staging:
          requires:
            - build
          filters:
            tags:
              only: /staging/
            branches:
              ignore: /.*/
